# Conexión a MongoDB

In [1]:
from pymongo import MongoClient
import pandas as pd

client = MongoClient("mongodb://localhost:27017/")
db = client["empresa"]
collection = db["empleados"]

# Limpiar colección
collection.delete_many({})

DeleteResult({'n': 0, 'ok': 1.0}, acknowledged=True)

# CREATE

In [2]:
empleados = [
    {"nombre": "Juan", "departamento": "Ventas", "salario": 8000},
    {"nombre": "Ana", "departamento": "RH", "salario": 9000},
    {"nombre": "Luis", "departamento": "IT", "salario": 12000},
    {"nombre": "Sofia", "departamento": "Ventas", "salario": 8500},
    {"nombre": "Carlos", "departamento": "IT", "salario": 11000},
    {"nombre": "Maria", "departamento": "RH", "salario": 9500},
    {"nombre": "Pedro", "departamento": "Ventas", "salario": 7800},
    {"nombre": "Laura", "departamento": "IT", "salario": 13000},
    {"nombre": "Diego", "departamento": "RH", "salario": 9200},
    {"nombre": "Elena", "departamento": "Ventas", "salario": 8700}
]

collection.insert_many(empleados)
print("Empleados insertados")

Empleados insertados

# READ

In [3]:
consulta = list(collection.find({"departamento": "Ventas"}))
df_read = pd.DataFrame(consulta)

print("Empleados del departamento Ventas:")
df_read

Empleados del departamento Ventas:

                        _id nombre departamento  salario
0  69d08aca8e8dec10f97279dd   Juan       Ventas     8000
1  69d08aca8e8dec10f97279e0  Sofia       Ventas     8500
2  69d08aca8e8dec10f97279e3  Pedro       Ventas     7800
3  69d08aca8e8dec10f97279e6  Elena       Ventas     8700

# UPDATE

In [4]:
collection.update_one(
    {"nombre": "Juan"},
    {"$set": {"salario": 10000}}
)

print("Salario actualizado")

# Verificar cambio
df_update = pd.DataFrame(list(collection.find({"nombre": "Juan"})))
df_update

Salario actualizado

                        _id nombre departamento  salario
0  69d08aca8e8dec10f97279dd   Juan       Ventas    10000

# DELETE

In [9]:
collection.delete_one({"nombre": "Pedro"})

print("Empleado eliminado")

# Verificar eliminación
df_delete = pd.DataFrame(list(collection.find()))
df_delete

Empleado eliminado

                        _id  nombre departamento  salario
0  69d08aca8e8dec10f97279dd    Juan       Ventas    10000
1  69d08aca8e8dec10f97279de     Ana           RH     9000
2  69d08aca8e8dec10f97279df    Luis           IT    12000
3  69d08aca8e8dec10f97279e0   Sofia       Ventas     8500
4  69d08aca8e8dec10f97279e1  Carlos           IT    11000
5  69d08aca8e8dec10f97279e2   Maria           RH     9500
6  69d08aca8e8dec10f97279e4   Laura           IT    13000
7  69d08aca8e8dec10f97279e5   Diego           RH     9200
8  69d08aca8e8dec10f97279e6   Elena       Ventas     8700